Vagrant.configure("2") do |config|

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "centos/7"
    vm2.vm.hostname = "vm2"	 
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
      vb.memory = "2048"
    end
  config.vm.provision "shell", path: "script.sh", privileged: false
  end
end

