Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.hostname = "vm1"	 
    vm1.vm.provider "virtualbox" do |vb|
    vb.name = "vm1"
    vb.memory = "2048"
  end

  vm1.vm.provision "shell", inline: <<-SHELL
      apt update
      sudo apt install net-tools
      sudo apt install traceroute
    SHELL
  end
end

