Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "jbs#{i}" do |jbs|
      jbs.vm.box = "centos/7"
      jbs.vm.network "private_network", ip: "192.168.1.1#{i}",
        subnet: "255.255.255.0"
      jbs.vm.hostname = "jbs#{i}"	 
      jbs.vm.provider "virtualbox" do |vb|
        vb.name = "jbs#{i}"
        vb.memory = "2048"
      end
      jbs.vm.provision "shell", path: "jbs.sh"
    end
  end

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.network "private_network", ip: "192.168.1.10",
      subnet: "255.255.255.0"
    web.vm.hostname = "web"	 
    web.vm.provider "virtualbox" do |vb|
      vb.name = "web"
      vb.memory = "2048"
    end
    web.vm.provision "shell", path: "web.sh"
  end
end
