Vagrant.configure("2") do |config|

  config.vm.define "vm" do |vm|
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 80, host: 8081
    config.vm.network "forwarded_port", guest: 443, host: 8082
    vm.vm.box = "centos/7"
    vm.vm.hostname = "vm"	 
    vm.vm.provider "virtualbox" do |vb|
      vb.name = "vm"
      vb.memory = "4096"
    end
  config.vm.provision "shell", path: "script.sh", privileged: false
  end
end

